apiVersion: batch/v1
kind: CronJob
metadata:
  name: govwatch-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: govwatch
              image: docker.io/dlaudfuf33/govwatch:latest
              args: ["update-default"]
              envFrom:
                - secretRef:
                    name: govwatch-env
          restartPolicy: Never
